In [3]:
import numpy as np
arr1=np.array([1,3,5,2])
arr2=np.array([[1,2,3],[2,5,6]])
print(arr1)
print("\n")
print(arr2)

[1 3 5 2]


[[1 2 3]
 [2 5 6]]


In [4]:
print(arr1.ndim)
print(arr2.ndim)

1
2


In [5]:
print(arr1.size)
print(arr2.size)

4
6


In [6]:
print(arr1.dtype)
print(arr2.dtype)

int32
int32


In [7]:
print(arr1.shape)
print(arr2.shape)

(4,)
(2, 3)


In [8]:
print(arr1.itemsize)
print(arr2.itemsize)

4
4


In [9]:
print(arr1.data)
print(arr2.data)